-- Create users table for the PostgreSQL-backed PHP PDO API
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'teacher' CHECK (role IN ('teacher', 'super_admin')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed default accounts
-- NOTE: Replace the placeholder hashes with the output of PHP password_hash('your-password', PASSWORD_DEFAULT)
INSERT INTO users (id, name, email, password, role) VALUES
(1, 'AI Kisa Admin', 'admin@aikisa.edu.pk', '$2y$10$EXAMPLEDUMMYHASHFORDEMO11111111111111111111111111111', 'super_admin'),
(2, 'Areeba Nadeem', 'areeba.nadeem@aikisa.edu.pk', '$2y$10$EXAMPLEDUMMYHASHFORDEMO22222222222222222222222222222', 'teacher')
ON CONFLICT (id) DO NOTHING;
